//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw1Plan.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gla43158_QLSXCW1Entities : DbContext
    {
        public gla43158_QLSXCW1Entities()
            : base("name=gla43158_QLSXCW1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dev_Lang> Dev_Lang { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Plan_Input> Plan_Input { get; set; }
        public virtual DbSet<Plan_View> Plan_View { get; set; }
        public virtual DbSet<BOM_BomTp> BOM_BomTp { get; set; }
        public virtual DbSet<BOM_ThiTruong> BOM_ThiTruong { get; set; }
    }
}
