//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw1Plan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Input
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan_Input()
        {
            this.Plan_View = new HashSet<Plan_View>();
        }
    
        public int IdInput { get; set; }
        public string Line { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProduceItem { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ShipDate { get; set; }
        public string Note { get; set; }
        public string CustomerOrder { get; set; }
        public string PurchaseRequisition { get; set; }
        public Nullable<System.DateTime> ProduceDate { get; set; }
        public string ThiTruong { get; set; }
        public string UserName { get; set; }
        public string UserNameEdit { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_View> Plan_View { get; set; }
        public virtual BOM_BomTp BOM_BomTp { get; set; }
        public virtual BOM_ThiTruong BOM_ThiTruong { get; set; }
    }
}
